language: java
matrix:
    include:
        - os: linux
          dist: bionic
          jdk:
              - openjdk11
          after_success:
              - mvn clean test jacoco:report coveralls:report

        - os: linux
          dist: xenial
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-6
                      - g++-6
                      - libstdc++6
          env: CC=gcc-6 CXX=g++-6
          jdk:
              - openjdk8

        - os: osx
          osx_image: xcode10.2


jobs:
    allow_failures:
        - dist: trusty


## Uncomment section below and the packages above to build unreleased snapshots of karmaresearch/vlog into vlog4j-base jar
before_install:
  - sh: ./build-vlog-library.sh

install: mvn install $OPTIONS -DskipTests=true

sudo: false

cache:
  directories:
    - ./local_builds
    - $HOME/.m2
